### ISSUE TITLE
Abstraer objeto tipo `GeoJSON`

### ISSUE THREAD

**Issue by edoomm** [TT2024-B106/stmeasures#35]
### TODO

Abajo todo el debraye de ideas que tuve, pero acá te dejo lo que importaría ir teniendo con este issue jajaja

- [x] Crear módulo/directorio `stmeasures.abstractions`
- [x] Implementar clase/archivo `stmeasures.abstractions.geojson` (abstrayendo las trayectorias y todas las propiedades que tiene: id, timestamp, etc)
- [x] Crear módulo/archivo `stmeasures.read`
- [x] Implementar función `stmeasures.read.file` i.e.: `def file(filepath: str) -> stmeasures.abstractions.geojson`

### Ideas

- [x] Crear módulo/archivo `stmeasures.read`, para poder leer GeoJSONs: `def file(filepath: str) -> stmeasures.abstractions.geojson` y este sería llamado a través de `stmeasures.read.file` que a su vez podría leer `stmeasures.read.json_file` (archivos JSON) y/o `stmeasures.read.geojson_file` (archivos GeoJSON) (esto ya es más cagada alocada, hazlo como mejor lo veas xd)
- [x] Crear módulo/objeto `stmeasures.abstractions.geojson` (El módulo `stmeasures.abstractions` también podría contener `trajectory`, `matrix` o cualquier otra abstracción/objeto que necesitemos, aunque de momento estas solo se utilizarán para C, quizás `trajectory` sí se necesite tanto en Python como en C)
- [x] Plus: Dibujar trayectoria en [geojson.io](https://geojson.io/) (quizás a través de otro módulo `stmeasures.visualize`)

El plus muy cabrón para este módulo sería poder hacer (y la idea en alto nivel de lo que podríamos hacer al final con nuestra librería):

```py
gs1 = stmeasures.read.file("ecatepec.geojson")

stmeasures.visualize.trajectory(next(gs1.trajectories)) # Visualiza la primer trayectoria del arreglo de trayectorias que el geojson tiene
stmeasures.visualize.trajectories(gs1) # Ya esto estaría más cabrón, pero lo podemos ir trabajando, pero esto te dibujaría todas las trayectorias

# Y ya algo más que podríamos hacer al final
stmeasures.visualize.trajectories(gs1.find_similar(next(gs1.trajectories))) # Visualiza todas las trayectorias similares a la primer trayectoria
```
