### ISSUE TITLE
Actualizar LCSS y EditDIstance

### ISSUE THREAD

**Issue by edoomm** [TT2024-B106/stmeasures#46]
- [x] Utilizar `cstructures` en Python y C (quitar warnings)
- [x] Agregar validaciones (hecho en #43)
- [x] Manejar excepciones (hecho en #43)
- [x] Actualizar docstrings a estilo [sphinx](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html) (hecho en #43)
- [x] Agregar archivos `.rst` para generar documentación
